// .res entries (25):35
gfx/env/ntdm2_bk.tga
gfx/env/ntdm2_dn.tga
gfx/env/ntdm2_ft.tga
gfx/env/ntdm2_lf.tga
gfx/env/ntdm2_rt.tga
gfx/env/ntdm2_up.tga
models/ze_escapeby_death/rockgibs.mdl
models/ze_escapeby_death/palma.mdl
models/ze_escapeby_death/pi_fern.mdl
models/ze_escapeby_death/woodgibs.mdl
models/zombie_anthill/corpse1.mdl
models/zombie_anthill/corpse2.mdl
models/zombie_anthill/corpse3.mdl
models/zombie_anthill/corpse4.mdl
models/zombie_anthill/corpse5.mdl
sound/ambience/silo_wind_loop.wav
sound/zombie_anthill/almost_noiseup.wav
sound/zombie_anthill/com_go_noiseup.wav
sound/zombie_anthill/fallback_noiseup.wav
sound/zombie_anthill/helicopter.wav
sound/zombie_anthill/resident_evil_main_theme.wav
sound/zombie_anthill/ze_ambiance1.wav
sprites/enter1.spr
sprites/muzzleflash2.spr
sprites/rifle_smoke3.spr
gfx/detail/dt_conc.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_wood1.tga
overviews/ze_escapeBy_death_b7a.bmp
overviews/ze_escapeBy_death_b7a.txt
maps/ze_escapeBy_death_b7a.txt
maps/ze_escapeBy_death_b7a_detail.txt

